# -*- coding: utf-8 -*-
"""Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPkAoy8ezdIEGLb8mKh73RAwK5qDhLsC
"""

import pandas as pd

data = {
    "Product Name" : ["Apples","Mango","Strawberry","Grapes","Dragonfruit"],
    "Date" : ["2023-07-01","2023-07-02","2023-07-03","2023-07-04","2023-07-05"],
    "Quantity" : [10,15,12,8,20],
    "Price_per_kg" : [140,170,75,60,100],
}
df=pd.DataFrame(data)

#Calculate total price for each items
df["Total_price"] = df["Quantity"]*df["Price_per_kg"]

print("Dataset :\n",df,"\n")
total_revenue = df['Total_price'].sum()

#Identify Best Selling Product by total price
best_product = df.groupby('Product Name')['Total_price'].sum().idxmax()
print("Best Selling Product:", best_product)

daily_sales = df.groupby('Date')['Total_price'].sum().reset_index()
print("\nDaily Sales Trend:\n", daily_sales)