# -*- coding: utf-8 -*-
"""Student_performance_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgDQnRNCxCPQZvKihtWetirAzxpTAPfR
"""

import pandas as pd

data = {
    "Name" : ["John","Bala","Hari","Kathir","Devi"],
    "Maths" : [78,56,90,93,45],
    "Science" : [91,67,87,94,68],
    "Social" : [87,88,98,99,78]
}
df = pd.DataFrame(data)
print("Students Marks\n",df)

subject_avg = df[["Maths","Science","Social"]].mean()
print("Subject Average\n",subject_avg)

df["Total"]=df[["Maths","Science","Social"]].sum(axis=1)
print("Students Marks\n",df)
Average=df["Total"]/3
print("Average\n",df["Average"])

top_student = df.loc[df["Average"].idxmax(),"Name"]
print("Topper of the class is :",top_student)